/**
 * UTILS.JS
 * Purpose: Handles Excel uploads and triggers the Master AI computation.
 * Strategy: Saves all model results to localStorage for instant page navigation.
 */

const uploadForm = document.getElementById('upload');

if (uploadForm) {
    uploadForm.onsubmit = async (e) => {
        e.preventDefault();
        const formData = new FormData(e.target);
        
        // Show initial loading state on the button
        const uploadBtn = document.getElementById('upload-btn');
        if (uploadBtn) {
            uploadBtn.innerText = "UPLOADING...";
            uploadBtn.disabled = true;
        }

        try {
            // 1. Upload the Excel file to the Node.js server (Multer)
            const res = await fetch('http://localhost:3000/upload', {
                method: 'POST',
                body: formData
            });
            const result = await res.json();
            
            if (result.filename) {
                // 2. Save the unique filename generated by Multer
                localStorage.setItem("uploadedFilename", result.filename);
                
                // 3. Inject the "Start Model" button into the runPy div
                const target = document.getElementById('runPy');
                target.innerHTML = `<button id="toPy" class="btn-success">START THE MODEL</button>`;
                
                // 4. Attach the Master AI trigger to the new button
                document.getElementById('toPy').onclick = () => runMasterAI(result.filename);
                
                if (uploadBtn) uploadBtn.innerText = "UPLOAD SUCCESSFUL";
            } else {
                alert("Upload failed: No filename received from server.");
                if (uploadBtn) {
                    uploadBtn.innerText = "Upload to Server";
                    uploadBtn.disabled = false;
                }
            }
        } catch (err) {
            console.error("Upload process error:", err);
            alert("Failed to connect to Node.js server.");
        }
    };
}

/**
 * Triggers the Python FastAPI Master Endpoint
 * Saves all results (Forecaster, Marketer, Influence) to localStorage at once.
 */
async function runMasterAI(filename) {
    const overlay = document.getElementById('loading-overlay');
    const btn = document.getElementById('toPy');

    // Show the full-screen AI computation overlay
    if (overlay) overlay.style.display = 'flex';
    if (btn) {
        btn.innerText = "AI PROCESSING...";
        btn.disabled = true;
    }

    try {
        console.log("Requesting Master AI computation for:", filename);
        
        // 5. Call the FastAPI Master Endpoint on port 8000
        const res = await fetch(`http://127.0.0.1:8000/process-all/${filename}`);
        const allResults = await res.json();
        
        if (res.ok) {
            // 6. SAVE ALL MODEL DATA TO LOCALSTORAGE
            // This allows all other pages to load data instantly without more fetch calls
            localStorage.setItem("masterAIData", JSON.stringify(allResults));
            
            console.log("AI Analysis Complete. Data saved to browser memory.");
            
            // 7. Final Redirect to the main dashboard
            window.location.href = "homepage.html";
        } else {
            throw new Error(allResults.detail || "AI Processing Failed");
        }
    } catch (err) {
        console.error("Master AI Error:", err);
        alert("Failed to process data: " + err.message);
        
        // Hide overlay and reset button if something goes wrong
        if (overlay) overlay.style.display = 'none';
        if (btn) {
            btn.innerText = "START THE MODEL";
            btn.disabled = false;
        }
    }
}